export const COURSES = [
  {
    id: "python-ai-basics",
    title: "Python for AI",
    description: "Learn Python programming fundamentals for AI and machine learning",
    instructor: "Dr. Sarah Johnson",
    level: "Beginner",
    duration: "4 weeks",
    lessons: 24,
    students: 1250,
    rating: 4.9,
    price: 199,
    image: "/images/courses/python.jpg",
    skills: ["Python", "Programming", "AI Basics"],
    tags: ["python", "beginner", "programming"],
  },
  {
    id: "machine-learning-101",
    title: "Machine Learning 101",
    description: "Master the fundamentals of machine learning algorithms and techniques",
    instructor: "Prof. Michael Chen",
    level: "Beginner",
    duration: "6 weeks",
    lessons: 36,
    students: 2100,
    rating: 4.8,
    price: 299,
    image: "/images/courses/ml-101.jpg",
    skills: ["Machine Learning", "Algorithms", "Scikit-learn"],
    tags: ["machine-learning", "beginner"],
  },
  {
    id: "deep-learning-with-tensorflow",
    title: "Deep Learning with TensorFlow",
    description: "Build deep neural networks using TensorFlow and Keras",
    instructor: "Dr. Alex Rodriguez",
    level: "Intermediate",
    duration: "8 weeks",
    lessons: 48,
    students: 890,
    rating: 4.9,
    price: 399,
    image: "/images/courses/tensorflow.jpg",
    skills: ["Deep Learning", "TensorFlow", "Keras"],
    tags: ["deep-learning", "tensorflow", "intermediate"],
  },
  {
    id: "nlp-with-transformers",
    title: "NLP with Transformers",
    description: "Master Natural Language Processing using Transformer models",
    instructor: "Dr. Emily Watson",
    level: "Advanced",
    duration: "8 weeks",
    lessons: 48,
    students: 650,
    rating: 4.9,
    price: 499,
    image: "/images/courses/nlp.jpg",
    skills: ["NLP", "Transformers", "Hugging Face"],
    tags: ["nlp", "advanced", "transformers"],
  },
  {
    id: "computer-vision-masterclass",
    title: "Computer Vision Masterclass",
    description: "Advanced computer vision techniques and applications",
    instructor: "Prof. James Liu",
    level: "Advanced",
    duration: "10 weeks",
    lessons: 60,
    students: 420,
    rating: 4.95,
    price: 599,
    image: "/images/courses/cv.jpg",
    skills: ["Computer Vision", "OpenCV", "PyTorch"],
    tags: ["computer-vision", "advanced", "pytorch"],
  },
  {
    id: "reinforcement-learning",
    title: "Reinforcement Learning",
    description: "Build intelligent agents using reinforcement learning",
    instructor: "Dr. David Park",
    level: "Advanced",
    duration: "8 weeks",
    lessons: 48,
    students: 380,
    rating: 4.85,
    price: 549,
    image: "/images/courses/rl.jpg",
    skills: ["Reinforcement Learning", "Deep Q-Learning", "Policy Gradient"],
    tags: ["reinforcement-learning", "advanced"],
  },
];

export const WORKSHOPS = [
  {
    id: "llm-fine-tuning",
    title: "Fine-tuning Large Language Models",
    description: "Learn to fine-tune GPT and other LLMs for specific tasks",
    date: "2024-01-15",
    time: "6:00 PM - 8:00 PM",
    duration: "2 hours",
    instructor: "Dr. Sarah Johnson",
    spots: 30,
    booked: 28,
    image: "/images/workshops/llm-finetuning.jpg",
    tags: ["llm", "workshop", "finetuning"],
  },
  {
    id: "prompt-engineering",
    title: "Prompt Engineering Mastery",
    description: "Master the art and science of prompt engineering",
    date: "2024-01-22",
    time: "5:00 PM - 7:00 PM",
    duration: "2 hours",
    instructor: "Prof. Michael Chen",
    spots: 25,
    booked: 18,
    image: "/images/workshops/prompt-engineering.jpg",
    tags: ["prompt-engineering", "workshop", "ai"],
  },
  {
    id: "deploying-ml-models",
    title: "Deploying ML Models to Production",
    description: "Deploy and scale machine learning models in production",
    date: "2024-02-05",
    time: "7:00 PM - 9:00 PM",
    duration: "2 hours",
    instructor: "Prof. James Liu",
    spots: 35,
    booked: 22,
    image: "/images/workshops/deployment.jpg",
    tags: ["deployment", "workshop", "ml"],
  },
];
