export const PROGRAMS = [
  {
    id: "ai-fundamentals",
    title: "AI Fundamentals",
    description: "Master the core concepts of artificial intelligence and machine learning",
    duration: "8 weeks",
    level: "Beginner",
    price: 499,
    image: "/images/programs/ai-fundamentals.jpg",
    icon: "Zap",
    learningOutcomes: [
      "Understand AI and ML fundamentals",
      "Learn Python for AI",
      "Build your first ML model",
      "Deploy models to production",
    ],
    skills: ["Python", "Machine Learning", "Data Analysis"],
  },
  {
    id: "advanced-deep-learning",
    title: "Advanced Deep Learning",
    description: "Deep dive into neural networks and advanced deep learning architectures",
    duration: "10 weeks",
    level: "Advanced",
    price: 699,
    image: "/images/programs/deep-learning.jpg",
    icon: "Brain",
    learningOutcomes: [
      "Master neural network architectures",
      "Build transformer models",
      "Work with computer vision",
      "Deploy at scale",
    ],
    skills: ["Deep Learning", "TensorFlow", "PyTorch", "Computer Vision"],
  },
  {
    id: "nlp-mastery",
    title: "NLP Mastery",
    description: "Become an expert in Natural Language Processing and LLMs",
    duration: "10 weeks",
    level: "Advanced",
    price: 699,
    image: "/images/programs/nlp.jpg",
    icon: "MessageSquare",
    learningOutcomes: [
      "Master NLP concepts",
      "Work with LLMs and Transformers",
      "Build chatbots and AI assistants",
      "Fine-tune language models",
    ],
    skills: ["NLP", "LLMs", "Transformers", "Hugging Face"],
  },
  {
    id: "ai-career-bootcamp",
    title: "AI Career Bootcamp",
    description: "Complete program to launch your career in AI",
    duration: "16 weeks",
    level: "Beginner to Intermediate",
    price: 1299,
    image: "/images/programs/bootcamp.jpg",
    icon: "Rocket",
    learningOutcomes: [
      "Master AI/ML fundamentals",
      "Build production projects",
      "Interview preparation",
      "Career guidance and job placement",
    ],
    skills: ["AI", "ML", "Data Science", "System Design"],
  },
];

export const TRACKS = [
  {
    id: "machine-learning",
    title: "Machine Learning Engineer",
    description: "Path to become a Machine Learning Engineer",
    courses: 6,
    duration: "12 weeks",
    skills: ["Python", "ML", "Statistics", "Data Science"],
  },
  {
    id: "deep-learning",
    title: "Deep Learning Specialist",
    description: "Specialize in deep learning and neural networks",
    courses: 5,
    duration: "10 weeks",
    skills: ["Deep Learning", "PyTorch", "Computer Vision", "NLP"],
  },
  {
    id: "nlp-engineer",
    title: "NLP Engineer",
    description: "Master Natural Language Processing",
    courses: 5,
    duration: "10 weeks",
    skills: ["NLP", "LLMs", "Transformers", "Python"],
  },
  {
    id: "ai-engineer",
    title: "AI Engineer",
    description: "Full-stack AI Engineer path",
    courses: 8,
    duration: "16 weeks",
    skills: ["AI", "ML", "Backend", "DevOps"],
  },
];
